name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release / Node 18
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
